### ISSUE TITLE
Add functionality to exclude ID's from auto-ingestion

### ISSUE THREAD

**Issue by Mougk** [globaldothealth/list#1013]
Some cases (due to their uniqueness or complexity) will be erroneous and need curators to manually change them. Auto-ingestion will overwrite them with current workflow. 

Solution proposed:
Enable easy to configure way for curators to add **ID's** and **fields** that should not be included in auto-ingestion.

**Comment by attwad** [comment]
@Mougk I'm not sure I get the "ID and Fields" combination here, do you mean that curators should be able to say "for these cases IDs, do not ingest these fields" ? or something else? please clarify, thank you.

**Comment by Mougk** [comment]
Yes: "for these case IDs, do not ingest these fields" OR if there has been a manual change to a field by a curator, block updating manually changed fields for specific IDs during automated ingestion.

**Comment by attwad** [comment]
Okay thanks, that's an interesting use-case.

We haven't thought of a way to do that, we don't even know if something's ingested manually or automatically (the automated "ingester" account is jut another user treated as any other curator).

The simplest approach would be to have curators be able to "lock" a whole case (making it read-only basically), that's simple but doesn't cover the field granularity that you requested.

We could also consider curators just leaving that case "unverified" with a note saying "wrongly ingested case, pleaes ignore" or something like that. That's possible with the current system.

The proper "id+fields" match would require writing a specific design document on how to do this as there are quite a few edge cases I believe so it's non trivial.

@Mougk wdyt?

**Comment by Mougk** [comment]
Would the "lock" suggestion allow manual changes from curators on that file? If so, that's great! 

Id+fields would need to wait.

@attwad thoughts? 

@z023 and @outbreakprepared FYI

**Comment by attwad** [comment]
I was thinking the curator would "lock" the case after having done the manual changes that were needed yes.

**Comment by z023** [comment]
But what if there is new information for the case that ingestion would have added? It would be missed if the case was locked?

**Comment by axmb** [comment]
It'd likely be missed, @z023. If the total number of erroneous cases is low, that might be an acceptable consequence.

Alternatively, if the total number of bad cases is quite low, we could special case them in the parser. Because we're avoiding updates for cases specifically with UUIDs, it'd be simple enough to check for those IDs and skip in the parser. This is the simplest solution, IMO, allows (with a reduction in simplicity) to do field-wise skipping or special casing.

**Comment by attwad** [comment]
Yes that's the most straightforward approach, I can send an example for Japan now.

**Comment by axmb** [comment]
Sweet. I'd recommend using that approach, which is relatively simple, until there's evidence it'd be untenable.

@Mougk -- feel free to close this with that workaround in mind, or keep it around as a P2.

**Comment by WeronikaMichaluk** [comment]
Add 3 vertical dots next to the check box;
Need to find a way to mark an individual row to not only be removed ut to be reingested. 
 
Maybe take case ID in the dropdown for curators only should be something like “add to restricted/excluded list” 

**Next steps:**

Christopher Remmel gathers more information about what current curators are doing now. Will ask people familiar with the architecture. 

HTD to receive more ideas and suggestions.

**Comment by calremmel** [comment]
Shape of a proposed solution @WeronikaMichaluk @gtuli:

1. For each raw data source, store information about cases to be excluded.
  1a. For sources **with IDs**, record the IDs.
  2a. For sources **without IDs**, store the entire row/record.
2. For each parser, if any case is in the associated set for exclusion, do not parse case.
  2a. Cases to search may be filtered by date in order to reduce number of cases to check

**Question**

When a curator selects a case to be excluded using the portal, how is that case identified and added to this list?

Thoughts:
 - Perhaps a set of IDs can be assigned by us to the raw source at the point of ingestion
 - This "raw source row/record ID" can then be linked to the MongoDB ID assigned during the parsing step
 - When a case is excluded, the mongo ID can then be matched to the raw source row/record ID, which can then be associated with the stored (id/row/record) in the raw source

_Very_ open to more ideas. Many thanks all.

**Comment by z023** [comment]
I think it'll mostly be excluding cases from sources **with** UUIDs.

**Comment by rpoltorak** [comment]
According to our discussion from yesterday, we would like to describe the shape of the solution @calremmel @iamleeg:

The first part of the task is to handle the "ideal" path to deal with the sources that have records with unique IDs. 
This scope of that part could be divided into two following parts:

### 1. Exclusion
This is a process when the curator excludes a particular case. 

#### User stories:
As a user, I want to exclude the selected case from the list, so it can be ignored in the ingestion and parsing process.
As a user, I want to put a note about that case, so it could remind me what was the reason for the exclusion.
As a user, I want to see the status indicators of the excluded cases on the list, so they can be easily recognized.

#### Actions needed:
**Front-end:**
- Introduce additional (for example. "exclude") action to the existing context menu located on every single row (three dots).
- Introduce a modal after clicking the "exclude" button. Modal should have an input/textarea for the note and the confirmation button.
- Introduce a new status and indicator state for the excluded cases (first column in the list). So there would be 3 statuses instead of 2: "unverified - U", verified - V, excluded - E".
- Optional: excluded cases could be greyed out a little bit (opacity: 0.8?)

**Back-end:**
- Introduce a new endpoint in data-service to exclude the cases
- The new endpoint should take a collection of cases:
	
```
[
        {
               sourceId: string,
               sourceEntryId: string, 
               confirmedDate: Date,
               curator?: string,
               note?: string
        },
        ...
]
```
- Store the excluded cases in a separate MongoDB table.


### 2. Case filtering on the parser level
This is a process where the parser ignores the excluded cases.

**Back-end:**
- Introduce a new endpoint in data-service to return excluded cases filtered by:
**date, sourceId**. 
- Data exclusion should happen on the parsing_lib level
- Cases that match the returned excluded list should be ignored.

### What's next?
The second part of this task is to adjust it for the sources that return cases without unique IDs.

### Questions
- Is it possible to reach the data-service endpoints easily on the parsing_lib level? Probably the answer is yes, but we have to check this.
- How do we recognize excluded cases from the UI perspective? Two options: 
  - Change and save the status of selected cases in the existing "cases" MongoDB table during the exclusion process.
  - Fetch the excluded cases along with normal cases and "match" them before rendering the list.

**Comment by calremmel** [comment]
@rpoltorak Thanks for all of your hard work on this! Just writing to let you know that I've seen this and will get you some answers tomorrow morning EST when I can. The shape of things at a glance looks good.

@iamleeg If you have a chance to give the questions a look before I get to it, please feel free.

For question 1, I believe the answer is yes as well but would need to check for the details.

For question 2, I think the idea of saving the status in the "cases" table makes a lot of sense. I think it would be great to add an element to an existing field if possible, but a schema alteration is certainly doable if necessary.

**Comment by iamleeg** [comment]
Looks great! I think there's a missing story: as a curator, I want to re-include a case that has previously been accidentally excluded, or where the exclusion is no longer appropriate.

1. yes it is, the parser lib already uses the upsert API for pushing parsed cases to the data service.
2. I agree with @calremmel that this is best done by saving the status in the table.

**Comment by rpoltorak** [comment]
Thank you all for your quick insight and response!

Regarding question 2: Ok, so it's decided. We're gonna save the status in the existing "cases" table.

@iamleeg You're totally right, thank you for reminding that. So we need to add the following user story:
- As a user, I want to include the already excluded case, so it will be taken into account in the parsing process once again.

@calremmel @iamleeg 
By the way, we have some new thoughts regarding the topic:

1. What do you think of adding the reason for the exclusion to the tooltip on hover event on the status indicator element? (U, V, E)
2. Do we need to save the date of the exclusion and show it in the tooltip mentioned in the previous question? We think that additional information about the date could be helpful to the curator. What do you think?
3. There is another thing that came to our mind about the excluded cases. Do you think it would be helpful to have some kind of switch in the UI (or another filter) so the curator can filter out the excluded cases from the results that are displayed on the list? This is the use case where there is a significant number of excluded cases (because they are for example duplicates) so they could distract the curator.

**Comment by iamleeg** [comment]
1. yes, sounds good.

2-5 all sound like questions for the domain expert curators @Mougk @z023 @SandraAdele so I won't speak for them. I'll note that because we use the [document version pattern](https://www.mongodb.com/blog/post/building-with-patterns-the-document-versioning-pattern) the date/time at which an exclusion is added or removed would automatically be recorded in the database, so the questions are do we want to store it in the document and do we want to show it in the UI.

Thanks!

**Comment by Mougk** [comment]
_Do we need to save the date of the exclusion and show it in the tooltip mentioned in the previous question? We think that additional information about the date could be helpful to the curator. What do you think?_

Yes

_There is another thing that came to our mind about the excluded cases. Do you think it would be helpful to have some kind of switch in the UI (or another filter) so the curator can filter out the excluded cases from the results that are displayed on the list? This is the use case where there is a significant number of excluded cases (because they are for example duplicates) so they could distract the curator._

Yes, filtering would be helpful

_Should we include the case with excluding more than one case from the user perspective? Now, we could verify/unverify many cases at once from the context menu at the top of the list. We could introduce an additional icon there._

Yes, selecting more than one is helpful.

_After re-including the case, should we change it's status to verified or unverified?_

Unverified
