### ISSUE TITLE
Style the hover state for country

### ISSUE THREAD

**Issue by dakrownie** [globaldothealth/list#1070]
Need design 

[Link to beta testing blocker list](https://docs.google.com/spreadsheets/d/1wM6se-GPNic3xxyggXPEsk0W6qMo6zl_RRcEwU6OcoU/edit#gid=1506108781)

**Comment by dakrownie** [comment]
Assigned to tommyshimko@google.com

**Comment by sratcliffe118** [comment]
@shroothless any update, please add mock to the issue

**Comment by shroothless** [comment]
See hover state [here](https://www.figma.com/file/tfBStxWn2bORj0RyJD0zaB/User-Study-Sept-21?node-id=1%3A843)

![image](https://user-images.githubusercontent.com/67452108/93883675-e2a28700-fcaf-11ea-9c9f-f84ad1a44028.png)

**Comment by lmanul** [comment]
Hmm, the mock is a little confusing because:

* The bug title mentions "hover state for country" but the mocked up pop-up shows information about a city.
* The map shown looks like it's an aggregate map (2D, country-wide case numbers), so only with per-country info.
* A per-country pop-up would not show a single latitude/longitude pair.
* Stockholm is quite far away from where the pop-up is shown :-D

So I'm going to style the pop-ups in the aggregate map to look close to this, but they will only contain the country name and case count.

**Comment by lmanul** [comment]
Fixed in https://github.com/globaldothealth/viz/commit/5de26846fe257f226130d22f94e556702fde9b9a -- please file more bugs if more things need to be tweaked :-)
