### ISSUE TITLE
Display counts/percentage coverage of available fields by country in Map

### ISSUE THREAD

**Issue by dakrownie** [globaldothealth/list#1074]
[Link to beta testing blocker list](https://docs.google.com/spreadsheets/d/1wM6se-GPNic3xxyggXPEsk0W6qMo6zl_RRcEwU6OcoU/edit#gid=1506108781)

**Comment by shroothless** [comment]
The filters should only be available on the "Individual cases" tab

**Comment by lmanul** [comment]
I should probably start linking commits that aim to integrate the new data flow into the existing pipeline, since this is heavily dependent on getting the new data, with more per-case details.

**Comment by lmanul** [comment]
https://github.com/globaldothealth/common/commit/58b70e6bac4f77267ea66a288f21acff3ab844bb

https://github.com/globaldothealth/common/commit/3e1f5eb6366d7b614743c599e3252a62de18e072

https://github.com/globaldothealth/common/commit/82bf2e8521225787f99b8774577c5ec4c2a468f1

**Comment by calremmel** [comment]
This issue refers to filtering capabilities for the Map, rather than for Data.

The goals appear to be the following:
1. There is a list of filter criteria on the sidebar for the Map where the countries currently are
2. The user can see how many of the rows contain not nulls in the fields of interest (demographic, travel history, etc)
3. The user can filter for only those cases that contain not nulls for the fields of interest

There is also some requirement to download directly, but that of course will not be possible for the MVP.

How much of this do we think is feasible over the next month, if any? Perhaps at minimum the sidebar can draw from an aggregate table in MongoDB for the completion statistics, and the links can navigate to the search function in Data and pass through the required search terms? @rkassa @iamleeg

**Comment by calremmel** [comment]
@rkassa @Mougk @joe-brilliant Are we still planning on implementing something along these lines?

There is some interest, as this is precisely the feature that @fojackson8 has asked for here: #1440

Direct link to the slides for context: https://docs.google.com/presentation/d/1YExjOd8qDXQ-yZm0LDJJXw3doI_V9cQGtPnHipX9FiU/edit?usp=sharing

We wouldn't want to replace the country counts on the sidebar entirely as suggested I wouldn't think, as now that they are linked to Data and can be used to search and navigate, they're _really_ useful imo as is.

But, we could have it pop up on selection or something like that. i.e. you select a country, the field coverage appears on the sidebar with the selected country case count on top, and then you can x out of it to return to the country counts. Or perhaps tabs at the top of the sidebar like the slides suggest.


Let me know if this is something that you want to pursue! My instinct is that it can wait until post-launch, but if it's a priority let me know.

**Comment by joe-brilliant** [comment]
See also #1440 (cc @rkassa @iamleeg)
