### ISSUE TITLE
The download link is does not download - there are 3 ways to download data.  Discussion of which way this button will work

### ISSUE THREAD

**Issue by dakrownie** [globaldothealth/list#1076]
[](https://curator.ghdsi.org/cases
)

[Link to beta testing blocker list](https://docs.google.com/spreadsheets/d/1wM6se-GPNic3xxyggXPEsk0W6qMo6zl_RRcEwU6OcoU/edit#gid=1506108781)

**Comment by dakrownie** [comment]
@attwad: Calling your attention to this.

Tim: @allysonjp715 do you know anything about a broken download link?

Allyson: This is under data viz component, so I think this is on @manucornet@google.com page

Tim: ohhh, sorry I missed that. Alright then, not sure what's broken? That link is working but perhaps it's the reader role issue highlighted below that is the problem?

Allyson: not sure... @acansler @leslieleland to confirm the issue here

**Comment by acansler** [comment]
Correct, this was referencing the data viz component download button, which appears to now links to the portal.

**Comment by sratcliffe118** [comment]
Yes, we can close this

**Comment by leslieleland** [comment]
Thanks - I was going to triage these issues today since there were some
that were resolved from our discussion and others that were duplicates.
The tags on the github issues are more effective than the spreadsheet (our
first pass on sorting and prioritizing).  Appreciate everyone pitching in
to get our Launch list clarified.
