### ISSUE TITLE
Linelist very slow after clicking download button

### ISSUE THREAD

**Issue by sratcliffe118** [globaldothealth/list#1109]
**Describe the bug**
Line list site becomes very slow once the download button is clicked

**To Reproduce**
1. Clicked download on the line list
2. navigated to home and then back to line list
3. Tabbed down a few pages

**Expected behavior**
Navigation and page loads are quick

**Comment by attwad** [comment]
Is it though?
Perhaps my new computer is just too powerful.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/1255432/93747847-95fb7500-fbf7-11ea-8989-ea18d4653a37.gif)

**Comment by sratcliffe118** [comment]
Definitely quicker than mine.

Just tried again and it is better but still a degree of lag. Will downgrade to a P2 so we can keep track

**Comment by allysonjp715** [comment]
After the most recent change the UX is snappy and users can move to other tabs. However they cannot interact with the linelist table until the entire download is complete (it shows the table as loading until it is complete). Perhaps this is due to a connection to the Cases database already being used and we can't make two queries on the database at the same time?

**Comment by attwad** [comment]
We can definitely make two queries to the DB simulataneously, read queries shoudn't take a lock.

**Comment by allysonjp715** [comment]
After the last PR the download is fully functional, and any part of the UI can be interacted with during the download with no extra lag. This can be viewed now on prod 👍
