### ISSUE TITLE
Press links website

### ISSUE THREAD

**Issue by Mougk** [globaldothealth/list#1255]
1. No link to NYT article
2. Add more links to press: https://www.sciencemag.org/news/2020/02/scientists-are-racing-model-next-moves-coronavirus-thats-still-hard-predict
3. https://www.independent.co.uk/voices/coronavirus-covid-19-pandemic-outbreak-data-research-cdc-who-a9406281.html

**Comment by sratcliffe118** [comment]
@rkassa could you take a look at adding these links?

**Comment by Mougk** [comment]
@scarpino can you add any links to go to the press section. See small selection above.

**Comment by rkassa** [comment]
@scarpino @joe-brilliant 

There was no real "Press" section during the design process, AFAIK, other than the NYT panel on the About page.  Happy to improvize a solution, of course. Do we have a particular blurb/quote for the Science Mag and Independent articles?

Otherwise, the NYT quote is now linked and fixed.

**Comment by rkassa** [comment]
Closing in favor of #1382 

(cc: @joe-brilliant @JaredHawkins @scarpino )
