### ISSUE TITLE
Issue when merging Canada parser

### ISSUE THREAD

**Issue by AnyaLindstromBattle** [globaldothealth/list#1389]
Hi all,
An issue arose when I merged the Canada parser which was written quite a while back by @yinguohang. It had passed all the tests and been approved by AB but when I merged it there was an error in sam-deploy. See error here https://github.com/globaldothealth/list/runs/1467501031. Any idea why this might have happened?
Thanks.

**Comment by AnyaLindstromBattle** [comment]
This has now also happened with merging Para... @calremmel do you think you could take a look as a priority?

**Comment by AnyaLindstromBattle** [comment]
And for USA... https://github.com/globaldothealth/list/actions/runs/398981224

**Comment by calremmel** [comment]
Looking at this now! Time to check out some error codes...

**Comment by calremmel** [comment]
@AnyaLindstromBattle Figured out the problem. If you look at the template.yaml file, for the Estonia parser, there are two layers listed, which provide access to common functions. Everywhere else, there is only one. Because there is some overlap between these two layers, it caused an error.

I'll submit a change for this now, should clear things right up. Until it is merged, feel free to ignore these errors, as they have nothing to do with your parsers!

**Comment by AnyaLindstromBattle** [comment]
Aha excellent, well done and thanks @calremmel !
