### ISSUE TITLE
Update interstitial login/signup page to add email option, reference Google login and accept PP, TOS, Newsletter opt-in

### ISSUE THREAD

**Issue by joe-brilliant** [globaldothealth/list#1435]
![EkAGazHQ](https://user-images.githubusercontent.com/74671973/102642142-13a92100-4112-11eb-9ee7-b4100b9795d4.png)

On the interstitial login page:

- [ ] Change login button to Login with Google standard button (https://developers.google.com/identity/branding-guidelines , https://developers.google.com/identity/sign-in/web/build-button )

- [ ] Add a field and option for users to login with any email address, in addition to Google option. For the sake of simplicity for MVP, it's OK if this option creates a temporary user ID just for each session vs a true user account per se. The key requirements are that we capture an email address + acceptance of TOS, PP etc for any users to access the Data page (see below)

- [ ] Add language that says "by creating an account, I accept the Global.health TOS and Privacy Policy, and agree to be added to the newsletter", and store a record of user approval with email address aligned to legal protocol (final language and process TBD)

-
- [ ]

**Comment by zbigiman-htd** [comment]
@joe-brilliant Is it OK?

![screencapture-localhost-3002-2021-01-06-22_54_53](https://user-images.githubusercontent.com/69294239/103823577-a5051680-5072-11eb-8521-15d9bac93644.png)

**Comment by joe-brilliant** [comment]
@zbigiman-htd looks good thank you! Is the intended experience that the "accept" box is automatically checked? Depending on conversations today and follow-ups on slack we may want to add a field for email address in addition to Google and adjust some of the language (with no password or registration per se). Would be great to understand the possibility/complexity/implications/tradeoffs of this so we can make a decision on Friday's product call.  Thinking of another workaround, could we work out an edge case solution for people who don't have Gmail to request a link to the full data set if they email us agreeing to accept the same terms? cc @rkassa @calremmel @emcohn

**Comment by zbigiman-htd** [comment]
@joe-brilliant I was thinking that this option is not uncheckable, just information - by clicking the login button I accept terms...
If it has to be a checkbox, after clicking the login button with not checked checkbox there should be some validation text showed - "this checkbox is required..." or the login button should be disabled until the accept checkbox is not checked.

**Comment by joe-brilliant** [comment]
hi @zbigiman-htd @WeronikaMichaluk @calremmel per our call today, I updated the title of the issue and added a check box to reflect the inclusion of a non-Google account login option. We can remove the need for a link to FAQ for "why google?" as well. Any questions/considerations/suggestions please feel free to comment here. Thanks! cc: @emcohn

**Comment by joe-brilliant** [comment]
A few resources per today's call re: Amplify (thx for the linx @rkassa ! )  

https://docs.amplify.aws/

https://docs.amplify.aws/lib/auth/getting-started/q/platform/js#configure-your-application

**Comment by maciekz1996** [comment]
@joe-brilliant @rkassa @calremmel  I started implementing AWS Amplify in order to add the ability for the user to sign up/in using different email address than gmail. In the comments above I see that it should be a passwordless authentication, there is a solution for such a case in AWS Amplify however it requires adding custom logic via Lambda Functions. (Each time a user wants to sign in he is being sent an authentication code to the provided email address. Only after entering correct code the user is successfully authenticated).  So here is my question: Should I implement the solution described above or should I add normal email/password authentication ?

**Comment by joe-brilliant** [comment]
@maciekz1996 thanks for the update and question! I think we can keep the password approach if it will make it simpler and more consistent. Initially, the thought was that it might be too cumbersome to develop from scratch but Amplify might make it easy enough! Lets quickly discuss and decide on our sync

**Comment by calremmel** [comment]
@maciekz1996 Here is the info for how authentication is currently handled for the user roles. Solution currently uses passport and express:

https://github.com/globaldothealth/list/blob/main/verification/curator-service/auth.md

Looks like passport checks role settings in mongodb here:

https://github.com/globaldothealth/list/blob/7b14950e8631f9d583b1a5650bae3f2a6e21e791/verification/curator-service/api/src/controllers/auth.ts

Connection to mongodb initialized here:

https://github.com/globaldothealth/list/blob/ed8ff4c758649174fc83500df87a0fe78f86552d/verification/curator-service/api/src/index.ts

User info is stored in the users collection on MongoDB Atlas. I just sent you an invitation for access in case you need it. The schema is fairly simple, let me know if you have questions about it.

Please let me know if there is anything I am missing here and I will work to get it for you!

**Comment by maciekz1996** [comment]
@calremmel Thank you for all the info and for sending me an invite to mongoDB. I will read through those documents and let you know if there is anything missing for me to finish the authentication process.

**Comment by maciekz1996** [comment]
@calremmel Today on a call I mentioned the route that I used in order to authenticate new user in our API using different email than google. This route is present in this file:

https://github.com/globaldothealth/list/blob/7b14950e8631f9d583b1a5650bae3f2a6e21e791/verification/curator-service/api/src/controllers/auth.ts

Specifically lines 151 - 174

I think that each time a user is being authenticated then the function from the file above creates new user no matter if the user was previously registered or not and I'm wondering if it can stay this way for now. If this is an issue then I would need to have access to some other endpoint in the API in order to authenticate users.
