### ISSUE TITLE
Email notifications to curators aren't working in test or production

### ISSUE THREAD

**Issue by iamleeg** [globaldothealth/list#1472]
**Describe the bug**
I'm pulling out part of the conversation from #1402 to a different issue because it has a wider (though probably less urgent) impact and the fix needs a different implementation.

The failure underlying #1402 is that the backend is unable to send email updates on schedules being added or removed to sources. Background: we're making SMTP connections to Gmail, based on a username and password in the app secrets. [Doing this requires use of an app password or turning off a security feature](http://nodemailer.com/usage/using-gmail/), which apparently isn't in place. However, as the documentation says, gmail isn't really designed for use as an automated service anyway.

Separately, we're getting failures in CI due to the tests of the email-sending code. They still connect to an internet service (albeit a fake one that doesn't really send emails), and that connection is timing out.

**To Reproduce**
1. Go to https://curator.ghdsi.org
2. Click on Sources
3. Edit a source that doesn't have an AWS schedule.
4. Add your email address to the notification recipients for the source.
5. Add a schedule, e.g. `rate(1 day)`.
6. Check your email.

**Expected behavior**
The portal should not report an error, but that's a separate thing tracked in #1402. You should receive an email regarding the addition of the schedule.

**Actual behaviour**
No email is sent.

**Additional context**
In #1402 we discussed using an actual service for sending automated emails, and I think that's a good solution. My preference would be Amazon SES as we're already using a lot of Amazon infra, and the rates at which these notifications are generated will be so low as to not move any billing needles.

The unit tests for this code should mock the API locally, and not make actual connections even to test email services like ethereal.email, so that we know that failures are due to problems in the code.

**Comment by calremmel** [comment]
@WeronikaMichaluk @maciekz1996 It could be useful to move this process over to the same service we are using for the welcome emails once everything is in place. We can confirm as we set our new priorities now that G.h is out.

**Comment by maciekz1996** [comment]
@calremmel @iamleeg I think that as you said using AWS SES is the best solution for this issue considering we are already using this service for welcome emails. Regarding email tests failing due to timeout I've added bigger timeout in my recent PR to avoid the failed test, however once the AWS SES will be responsible for sending emails this problem will be gone too.

**Comment by iamleeg** [comment]
Sounds great, thanks!

**Comment by maciekz1996** [comment]
@iamleeg I've checked this issue and the reason that those notifications are not being sent is that in the local environment there is an error after updating source's AWS schedule rate before even reaching the point in code where notifications should be sent. You can see the error on the screenshot below. I guess that this is happening because `EVENT_ROLE_ARN` variable inside `verification/curator-service/api/src/util/validate-env.ts` (line 68) is set to `default-dev-arn` as the default value in dev environment. Once I commented out failing code, notifications where sent successfully. My guess is that this issue is not present on production, just locally because of this default ARN value. 

I'm not sure what value could this variable take in development environment so that the error wouldn't occur. Do you maybe have some ideas?

<img width="1875" alt="Screen Shot 2021-09-14 at 11 53 44" src="https://user-images.githubusercontent.com/44740625/133240014-99d0ec5f-1bf1-4fae-b542-64060fe377bf.png">

**Comment by iamleeg** [comment]
Thanks @maciekz1996, that's fine I'm happy to accept that's an error that will block emails getting sent locally. This was originally about our use of an unsupported interaction with Gmail in production so we weren't getting prod emails either. Now that we've changed to SES, I think this is fixed: let's mention that at the product meeting this afternoon in case anyone else knows of problems before we close the issue.
