### ISSUE TITLE
Create new Variant field for case

### ISSUE THREAD

**Issue by calremmel** [globaldothealth/list#1483]
**Requirements:**

- [x] The case schema should have a new field named variantOfConcern.
- [x] List of all possible variants should be stored in a csv file on GitHub.
- [x] Curators should be able to select variants from a dropdown populated from the csv from within the UI.
- [x] variantOfConcern should be added to the bulk upload template.

**Questions**

1. Should this be a top-level field, or nested inside of genomeSequences? i.e. `variant.name` vs `genomeSequences.variant.name`
2. Does this field need any attributes besides name?

**Comment by Mougk** [comment]
Name of field: 'Variant Of Concern (VOC)"

There are currently 3 of them that we are tracking (more to come). I am sending you a CSV via slack. 

Please store this CSV visibly so we can change it if new data becomes available.

**Comment by AnyaLindstromBattle** [comment]
Quick question regarding this. We are going to start uploading data with strain information using the bulk upload functionality in the curator portal. To do this we have to upload a csv with certain allowed column headers (see https://github.com/globaldothealth/list/tree/main/verification/curator-service/ui#bulk-upload-process). 

So my question is, once you've added variantOfConcern to the case schema, will this automatically become a valid column header for bulk upload? Asking because the bulk upload template currently doesn't have headers for all the information possible in the case schema. 

If not, this is something that should probably be added to this task.

**Comment by calremmel** [comment]
@AnyaLindstromBattle Great point! Will add.

**Comment by AnyaLindstromBattle** [comment]
Thanks @calremmel. Would it be possible to also add the other fields which are missing? That way the bulk upload function will allow for uploading fully specified cases, rather than limiting the amount of info that can be included as is currently the case
