### ISSUE TITLE
Add date and time to download CSV

### ISSUE THREAD

**Issue by Mougk** [globaldothealth/list#1509]
Currently the download file is called "latestdata.tar.gz' and when unzipped 'out', filename is 'latestdata.csv'.

I'd suggest we rename to "gh_YYYY-MM-DD.tar.gz"; "gh_YYYY-MM-DD" and filename "gh_YYYY-MM-DD.csv'

**Comment by calremmel** [comment]
@maciekz1996 If I were to make the tar.gz include the date, how difficult would it be to make the link dynamic as of when the file changes? I can output the location of the latest file to a static location if helpful, i.e. update a file on S3 called target.json or something like that which includes the most recent filename for the data.

@Mougk If this turns out to be tricky, would calling the file "gh_YYYY-MM-DD.csv" and then calling the tarball wrapper "gh_latest.tar.gz" or similar be a good compromise? Just as a plan B in case there are unforeseen challenges.

**Comment by Mougk** [comment]
Good with me

**Comment by maciekz1996** [comment]
@calremmel @Mougk Sorry for such a late response ! I've missed the notification 

I can think of two solutions for this issue right now that doesn't require storing the name of file anywhere:

* We can leave tar.gz file named as it is right now so: `latestdata.tar.gz` and change the name of the csv file. Then the link will  be static and I can add extra parameter to the S3 query to change the name of downloaded file to be `gh-YYYY-MM-DD.tar.gz`. So in conclusion the link would stay static and the end user would see the proper name on both files (the tar.gz wrapper and csv) 
* The second solution is that both files (csv and tar.gz) are named like `gh-YYYY-MM-DD` (UTC) and because of that the link to S3 bucket becomes dynamic. I can then obtain current YYYY-MM-DD UTC in every api call and "generate" this dynamic link based on that. 

Both of this changes should be quite easy to implement on my side, so just let me know whatever works for you best !

**Comment by calremmel** [comment]
@maciekz1996 Thank you for this! I think the first solution is perfect, very happy to know that is possible. Please do go ahead!
