### ISSUE TITLE
Fix ingestion issues relating to backfill

### ISSUE THREAD

**Issue by abhidg** [globaldothealth/list#1560]
Various parsers fail on ingestion when trying to backfill by @AnyaLindstromBattle 

- [x] Czechia: chunking puts an extra 'd' in the second line which causes it to crash
- [ ] Data download at source stage fails for Argentina
- [x] Germany: ECONNREFUSED 10.100.59.189:80 error sending cases to server
- [x]  Brazil Rio Grande do Sul: Some chunks throw IndexError (see below)
- [ ] Mexico, Germany, Sao Paolo: Timeouts for some chunks
- [ ] Investigate uneven chunk sizes for Mexico
- [ ] RGDS ECONNRESET error
- [ ] USA fix ingestion script
- [x] re-ingest missing line list exported cases
- [x] update data dictionary and add to downloads
- [x] update data agg script to serve VOC data to map
- [x] tackle geocoding fix
- [ ] repair and improve error logger

**Comment by Mougk** [comment]
@AnyaLindstromBattle can you try Mexico/Germany again to see whether there are timeouts for the chunks now that the chunk size has been reduced?

**Comment by AnyaLindstromBattle** [comment]
I just tried backfilling Germany and got the following - 
![image](https://user-images.githubusercontent.com/62887048/108206672-9ce2d100-711e-11eb-90a2-59faac72b8d7.png)
Think the same as the permissions issue w Mexico?

**Comment by calremmel** [comment]
**Status**

The ingestion infrastructure [currently works as follows](https://github.com/globaldothealth/list/tree/main/data-serving/data-service)(https://github.com/globaldothealth/list/tree/main/ingestion/functions/parsing):

1. A [retrieval function](https://github.com/globaldothealth/list/tree/main/ingestion/functions/retrieval) (AWS Lambda in Python) retrieves data (csv, json) from an external source and stores it in local filespace
2. It proceeds to divide it into chunks, uploads those chunks to S3, and then triggers simple [parsing functions](https://github.com/globaldothealth/list/tree/main/ingestion/functions/parsing) (also AWS lambda) on the chunks to mould them into a common format. These invocations are spaced out as much as possible in context of a 15 minute limit.
3. Each of these chunks are submitted to MongoDB Atlas via a [REST API written in node.js]().

**The Problem**

While the retrieval, chunking, upload to S3, and parsing are all working fine, upserting is not. Different submissions receive the follows error responses, which are a bit inconsistent:

1. socket hang up
2. ECONNREFUSED
3. ECONNRESET
4. 502 Bad Gateway

**What we are trying**

We are currently trying converting the lambda functions to AWS Batch jobs and slowing down the concurrency of the chunking, just in case that is the root of the problem.

**Why we want more help**

While the frequency of the invocations could be the root cause, I'm also not totally confident that it will resolve the problem on its own, and want to prepare for that possibility. I'm led to think this through perusing some links that suggest that either the server isn't being given enough time to respond, or is being overloaded through some other source:

https://stackoverflow.com/questions/41241938/nodejs-socket-hang-up-econnreset-http-post-request-from-meteor-to-node-js-se
https://stackoverflow.com/questions/16995184/nodejs-what-does-socket-hang-up-actually-mean

**Comment by calremmel** [comment]
> I just tried backfilling Germany and got the following -
> ![image](https://user-images.githubusercontent.com/62887048/108206672-9ce2d100-711e-11eb-90a2-59faac72b8d7.png)
> Think the same as the permissions issue w Mexico?

For anyone popping in who is new to the issue, this permissions issue is now long resolved :)

**Comment by abhidg** [comment]
I think moving to AWS batch will solve many of the issues. If connecting to upstream servers is an issue due to server load or too frequent attempts, then we can use exponential backoff waits on AWS batch. The curator UI does expect everything to finish in 20 minutes for a backfill, so we'll have to change that:
https://github.com/globaldothealth/list/blob/e1ab7d9176596506fd6f01e176dc217611e5c3a3/verification/curator-service/ui/src/components/AutomatedBackfill.tsx#L26

**Comment by abhidg** [comment]
Depends on #1634

**Comment by abhidg** [comment]
Closing, most of the issues related to AWS Lambda (chunking). The ECONNREFUSED error has popped up again, see issue #1745. Improving error logs is at #1564
