### ISSUE TITLE
Create customized GA dashboard and other KPI reports

### ISSUE THREAD

**Issue by joe-brilliant** [globaldothealth/list#1612]
TBC:

- Traffic
- Engagement
- Referrals 
- Sign-ups (users, newsletter, get involved)
- Downloads
- Conversion rates
- Cases, sources, coverage, completion

**Comment by joe-brilliant** [comment]
+ @jim-sheldon who just got added to our GA account to help ensure we're tracking all the key interaction and telemetry data (TIA!)

**Comment by maciekz1996** [comment]
@joe-brilliant In order to make sure that we can track all the events inside Google Analytics I would need access to Google Tag Manager. From what I've seen there isn't any Tag Manager account connected with GA right now. You can create one by going to this link: https://tagmanager.google.com/?utm_campaign=SuiteHeader&utm_source=UniversalPicker&utm_medium=getStarted#/home

**Comment by joe-brilliant** [comment]
This should be the tag manger link https://tagmanager.google.com/?utm_campaign=SuiteHeader&utm_source=UniversalPicker&utm_medium=getStarted#/admin/?accountId=6006340765&containerId=61719986&containerDraftId=2

**Comment by maciekz1996** [comment]
@joe-brilliant It seems like I don't have access to Google Tag Manager, could you please add me as a user there?

**Comment by joe-brilliant** [comment]
Invite just sent @***@***.******@***.***> let me know if you receive and can access
________________________________

**Comment by maciekz1996** [comment]
@joe-brilliant I got the invite, now I can asses GTM, thank you

**Comment by abhidg** [comment]
@maciej-zarzeczny can this be closed?
