### ISSUE TITLE
Daily metrics to keep track of data ingestion

### ISSUE THREAD

**Issue by fojackson8** [globaldothealth/list#1618]
We're ingesting new data each day from sources around the world, and adding to our database. We want to track the quality of new data, making sure our database continues to accurately reflect the COVID-19 situation in each country. 

There are a number of ways data ingestion can break. Any changes to the source dataset headers or format will throw errors which we can catch. But we currently have no process for detecting subtler changes to the cases reported in each country, for example if geocoding stops working, or if cases stop getting reported. This is important for QC, but also to get an ongoing sense of the case coverage we're getting in each country, how well this country is reporting new cases, and just general data exploration.

We want to create a daily summary of (at least some of) the following:

- Map of new cases
- Number of cases that are falling inside country/state boundary vs. outside
- Daily time series of cases ADI (state or country) and JHU (histogram daily, 7 day rolling average line on top)
- Daily number of cases ADI minus JHU (immediately spot difference)
- Number of cases with recorded travel history
- Global map of cases with travel history (last week, colour by date of confirmation): lat/long travel history to lat/long destination
- VoCs tracked

For more general data exploration purposes, it would also be good to generate:
- Heatmaps of Age/sex distribution through time
- Date onset to confirmation histograms with new cases highlighted

As well as generating these figures each day, we need to decide on best way medium to provide these summaries. Options include:

- Dedicated Slack channel
- Dedicated page on website
- PDF reports
- Somewhere else

**Comment by abhidg** [comment]
Here's a draft workflow:
1 -> 2 -> 3 -> 4, 1a -> 3

1. Download latestdata.csv (S3)
1a. Download JHU data
2. Split into smaller daily dataset and monthly dataset, unless we decide we need an overview of the full dataset everyday. These will be cached on the local filesystem.
3. Multiple quality checkers can run in parallel (AWS Batch, or if really quick, AWS Lambda) to put JSON output into database (separate quality collection?).
4. Data is consumed from the database to produce reports.

I think this structure is a good one, since we can have local testing as long as we setup a local MongoDB, with reports being presented as HTML/PDFs in step 4. Ideally, this would be integrated into the curator UI, but since that might take a while, we can get started with this workplan. Since the processed data is all going to be in a DB, should be easy to create nicer visualizations in the portal / another site.

**Comment by abhidg** [comment]
Case counts per day are now being posted to slack in e17cbb5f26e80984a6e6de91044bfb101daf9479, keeping open for advanced metric reporting.

**Comment by abhidg** [comment]
Some of this (map with timeseries) is implemented for hMPXV with the briefing report and the new timeseries view, and we have Slack reporting of daily data ingestion.
