### ISSUE TITLE
Get Involved form not working

### ISSUE THREAD

**Issue by joe-brilliant** [globaldothealth/list#1986]
- [x] Getting the following error message:  https://www.dropbox.com/s/zec8ispyuzqejxk/Screen%20Shot%202021-07-07%20at%209.04.28%20AM.png?dl=0 
- [x] Responses should go to info@global.health moving forward

**Comment by rkassa** [comment]
Ready for testing on dev:
https://dev-globalhealth.pantheonsite.io/about/

**Comment by rkassa** [comment]
Confirming: done and ready on dev @joe-brilliant

**Comment by joe-brilliant** [comment]
Just tried but didn't get any message to info@global.health @rkassa . Can we also make the confirmation message a bit easier to read (more contrast) and place it above the fold on a laptop?

https://www.dropbox.com/s/dq5q9n9t3a050w9/Screen%20Shot%202021-07-28%20at%206.56.12%20AM.png?dl=0

**Comment by rkassa** [comment]
@joe-brilliant , can you give me access to the info@global.health email address when you get a chance? i need to authorize it as an email sender for the “get involved” form. annoying security steps because pantheon’s dev URL doesn’t match the “info@global.health” email domain. That’s why emails are not sending

**Comment by rkassa** [comment]
messaging text is cleaned up:
![Screen Shot 2021-07-29 at 9 31 29 AM](https://user-images.githubusercontent.com/201428/127500969-91ccc49a-9cda-4695-8077-f1db3e0b4802.png)

**Comment by joe-brilliant** [comment]
I think we’re good to push to prod / close this out?

**Comment by rkassa** [comment]
on prod. closing.
