### ISSUE TITLE
Move data export to Batch

### ISSUE THREAD

**Issue by abhidg** [globaldothealth/list#2190]
We want to generate country specific exports using Batch. This has the following
advantages over the older system using AWS Lambda:

* Not limited to the 15 minute time limit of Lambda.
* Can generate country specific datasets according to the schedule in which they are updated in the database, rather than daily. As an example, the USA dataset is updated once a month.
* Not limited to a particular set of Python versions (due to Lambda architecture) as we'll generate a docker image to run the script.

The entire data export (that is currently broken, see #2191) will still be run daily, but now it just needs to combine the various csv.gz files and tar them together, which can be done in Batch as well.

For the country exports, we'll use a new [versioned S3 bucket](https://docs.aws.amazon.com/AmazonS3/latest/userguide/Versioning.html) named *covid-19-country-export* which will have `<country>.csv.gz` in a csv subfolder (similarly for json.gz if we add that).

The entire data export will still be served from the *covid-19-data-export* bucket, which will no longer have the processing subfolder.

Additionally, this work will help filtered downloads for large data sources when the user filters by country only.

**Comment by iamleeg** [comment]
Looks great! Particularly good to only regenerate the country CSVs on the schedule that the country is updated; to provide a meaningful division of cases in the files; and to support the filtered downloads feature with this change too. One addition (which doesn't block any work on this because we can add it later) is to work with Gal to find out whether we want to have retention limits for old data downloads, and to clean up legacy versions of the downloads.

**Comment by iamleeg** [comment]
(I mean, hopefully there aren't either policy or cost(!) reasons to get rid of old versions, to improve the reproducibility of results obtained using our data, but best to check)
