### ISSUE TITLE
UX for unknown fields

### ISSUE THREAD

**Issue by sratcliffe118** [globaldothealth/list#444]
Selecting Unknown makes no change to the field, just remains blank.
UX to confirm expected functionality and UX when selected.
See attached design currently.

![Screen Shot 2020-07-06 at 2 10 18 PM](https://user-images.githubusercontent.com/63205311/86596676-8a9e9300-bf92-11ea-8c9f-4914f44dd651.png)

**Comment by allysonjp715** [comment]
@shroothless we should sort out the UX pattern for unknown fields in general. Right now there are some dropdown fields that have "Unknown" values e.g. gender. In the database we have decided to leave this field as not set, rather than setting a value of "Unknown". 

In the UI do we want to have the option to specifically choose "Unknown" rather than not setting the field? We could also have both options (select "Unknown" or unselect that field) that translate to the same thing in the backend. But I'm a little wary that if people see an Unknown field they'll feel the need to select it for each field, where they could save time and leave it blank.

Did that all make sense? WDYT?

**Comment by shroothless** [comment]
We had decided that we wanted users to deliberately select Unknown and prioritize accuracy over efficiency. Since many of these fields are not required and the order of the fields doesn't necessarily match the source they are curating from. I'd prefer to keep the unknown option until we hear that it's really slowing people down.
