### ISSUE TITLE
Pathogens field is misleading and missing SARS-CoV-2

### ISSUE THREAD

**Issue by outbreakprepared** [globaldothealth/list#455]
**Is your feature request related to a problem? Please describe.**

Pathogens field is confusing I find. Also it is missing SARS-CoV-2 as a pathogen.

**Describe the solution you'd like**
Remove or pre-load with form that is specific to the disease of interest.

**Comment by allysonjp715** [comment]
I agree this is confusing. The intended data for this field is diseases *other* than the disease that is currently being tracked that the case has had. That's why you can't select SARS-CoV-2, since all cases in this DB will have it (SARS-CoV-2 == covid-19 right?). When we track other diseases, they will have their own DB. 

We should change the name of the UI section and/or add some description text to make that clear.

**Comment by sratcliffe118** [comment]
@outbreakprepared what should we call this field given the above

All covid-19 line list cases will have the pathogen SARS-CoV-2 appended to them by default. This is designed to capture any other pathogens reported in the case

**Comment by allysonjp715** [comment]
to nit-pick: currently SARS-CoV-2 *won't* be stored as a value in the pathogens field of the database. Since the entire database is for SARS-CoV-2 cases, we don't need to add it to every case. For a new disease, a new database instance will be created.

**Comment by abhidg** [comment]
The new data dictionary (#1610) notes that pathogens field will not contain SARS-CoV-2.
