### ISSUE TITLE
Chart: Days since most recent case confirmation by country, not updating

### ISSUE THREAD

**Issue by sratcliffe118** [globaldothealth/list#550]
New line list case added for India on 6th July (8 days prior). Chart has not updated, see screenshot
![Screen Shot 2020-07-14 at 12 43 19 PM](https://user-images.githubusercontent.com/63205311/87421912-9fe97200-c5cf-11ea-9397-e7f0a1d894da.png)

**Comment by khmoran** [comment]
Part of this issue comes from an env mismatch: the fact that entering new data into the dev curator portal will update dev mongodb, but the charts reflect prod (sorry!!)

That said, there have been csv commits in the last 28 days, so something is still wrong.

**Comment by sratcliffe118** [comment]
Ack on different environments, would be good to see the latest state of the
Prod data especially as we think about how we transition

Thanks,

Stephen



<https://sites.google.com/a/google.com/gps-email-signature/home/Google_Signature4.png?attredirects=0>

*  •  **Stephen Ratcliffe*

*  • * Google Pay, Product Manager

*  •  *sratcliffe@google.com

  •  Google, Inc.



*If you received this communication by mistake, please don't forward it to
anyone else (it may contain confidential or privileged information), please
erase all copies of it, including all attachments, and please let the
sender know it went to the wrong person. Thanks.*

**Comment by sratcliffe118** [comment]
Checked again today and no update

**Comment by khmoran** [comment]
The source of the issue is the CSV -- it isn't updating. There's a job that auto-updates it but it's not adding any bytes:  https://github.com/beoutbreakprepared/nCoV2019/commit/5cc3e455b95fd35ab18fd5a870941d207a47010e

I verified that downstream of the CSV (conversion & mongodb import) is working: I cloned the repo with the csv and checked the # of cases in it and it matches what we have in mongodb, and verified that the automated jobs to convert & import have succeeded

**Comment by khmoran** [comment]
cc @JaredHawkins to triage CSV update issues on the HM side

**Comment by JaredHawkins** [comment]
Once Thomas started his leave, I believe @attwad had been running these.  Is there any documentation of his process that I can point someone to?

**Comment by dakrownie** [comment]
@attwad please comment here.

**Comment by attwad** [comment]
@SpencerMarks-IDHA has been running the CSV generation job as an aws batch job since at least 2 weeks ago there's no need for me to run it anymore. Please check with him for the status of that job.

**Comment by sratcliffe118** [comment]
Has this been resolved? Can we close this out?

**Comment by SpencerMarks-IDHA** [comment]
I believe Chris Remmel fixed this.

**Comment by SpencerMarks-IDHA** [comment]
However, Chris is not a member of this repo so I can't show him this ticket/assign it to him.

**Comment by dakrownie** [comment]
I just pinged him on slack for his GutHub handle.

**Comment by calremmel** [comment]
Hi all! I believe the source of this problem is in the sheet cleaner script in the nCov2019 repo. My theory is that there is a pull command placed before an add/commit command which is continually overwriting the newly pulled file with the old one, which has been identical since the process was moved to AWS on June 29th.

I've submitted a PR on that repository, which is waiting for approval. As soon as it is accepted, I believe the problem will be solved.

**Comment by calremmel** [comment]
Hmm actually it looks like the PR was accepted, and the file is still the same length. I'll connect with Spencer and we'll give this another look.

**Comment by calremmel** [comment]
Update on this: the sheet cleaner script is actually working fine, it's the line list data source that is paused in terms of updates. I believe that for the time being this issue can be closed out!

**Comment by dakrownie** [comment]
@sratcliffe118 Is this good to be closed out?

**Comment by sratcliffe118** [comment]
Ack, yes closing as the data is not being updated. No technical issues
